use_default_settings: true
server:
  secret_key: "0e41832890cfacb97a67e63f146039b14891cdce9295bfb3cdfca29bb7aafae8"
  limiter: false
  image_proxy: false
search:
  safe_search: 0
  formats:
    - html
    - json
